# Workflow to Deploy EKS using Terraform
# Authored by : Sudhakar Mangipudi
# Created Date: 28-Mar-2023

name: Deploy EKS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.2
      - name: Initialize Terraform
        working-directory: aws/eks/
        run: terraform init
      - name: Plan the configuration
        working-directory: aws/eks/
        run: terraform plan
      #- name: Apply Terraform
      #  working-directory: eks/
      #  run: terraform apply -auto-approve
